services:
  alfasoft:
    container_name: "alfasoft"
    hostname: "alfasoft.localhost"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=alfasoft.loc
    restart: always
    working_dir: /var/www/html/alfasoft
    volumes:
      - ./docker/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./:/var/www/html/alfasoft
      - ~/.ssh:/tmp/ssh-keys
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash -c "cp /tmp/ssh-keys/* ~/.ssh && chmod 600 ~/.ssh/* && php-fpm"
    networks:
      - alfasoft-network

  alfasoft_nginx:
    image: nginx:stable-alpine
    container_name: "alfasoft_nginx"
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html/alfasoft
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - alfasoft
    networks:
      - alfasoft-network


networks:
  alfasoft-network:
    driver: bridge
